import { string, object, number } from "yup";

/**
 * contains all the validated environment variables.
 *
 * Reason:
 * This help prevents the application to start without environment variables. If not used you may still find the
 * error but a bit late.
 */

export const environment = object()
  .shape({
    chainid: string().default('pylons-testnet-3'),
    chainname: string().default('pylons'),
    rpc: string().default('http://localhost:26657'),
    rest: string().default('http://localhost:1317/'),
    bip44cointype: number().default(118),
    bech32prefixaccaddr: string().default('pylo'),
    bech32prefixaccpub: string().default('pylo'+'pub'),
    bech32prefixvaladdr: string().default('pylo'+'valoper'),
    bech32prefixvalpub: string().default('pylo'+'valoperpub'),
    bech32prefixconsaddr: string().default('pylo'+'valcons'),
    bech32prefixconspub: string().default('pylo'+'valconspub'),
    currenciescoindenom: string().default('BEDROCK'),
    currenciescoinminimaldenom: string().default('ubedrock'),
    currenciescoindecimals: number().default(6),
    currenciescoingeckoid: string().default('pylon'),
    feecurrenciescoindenom: string().default('BEDROCK'),
    feecurrenciescoinminimaldenom: string().default('ubedrock'),
    feecurrenciescoindecimals: number().default(6),
    feecurrenciescoingeckoid: string().default('pylon'),
    stakecurrencycoindenom: string().default('BEDROCK'),
    stakecurrencycoinminimaldenom: string().default('ubedrock'),
    stakecurrencycoindecimals: number().default(6),
    stakecurrencycoingeckoid: string().default('pylon'),
    gaspricesteplow: number().default(0.01),
    gaspricestepmedium: number().default(0.025),
    gaspricestephigh: number().default(0.03),
    gaspricestepaverage: number().default(0.03),
    denom: string().default('ubedrock'),
    displayDenom:string().default('bedrock'),
    baseDenom:string().default('ubedrock'),
    baseExponent: number().default(6),
    name: string().default('pylons'),
    prefix: string().default('pylo'),
    color: string().default('linear-gradient(to right, #ef4421,#0a0049 81%)'),
    explorer: string().default('https://pylons.explorers.guru/'),
    txExplorer: string().default('https://pylons.explorers.guru/transaction/'),
    valExplorer: string().default('https://pylons.explorers.guru/validator/'),
    govExplorer: string().default('https://pylons.explorers.guru/proposal/'),
    logo: string().default('/images/logo/pylons.png'),
    hyperLink: string().default('https://www.pylons.tech/home/')
  })
  .validateSync({
    chainid: process.env.NEXT_PUBLIC_CHAIN_ID,
    chainname: process.env.NEXT_PUBLIC_CHAIN_NAME,
    rpc: process.env.NEXT_PUBLIC_RPC,
    rest: process.env.NEXT_PUBLIC_REST,
    bip44cointype: process.env.NEXT_PUBLIC_BIP44_COINTYPE,
    bech32prefixaccaddr: process.env.NEXT_PUBLIC_BECH32_PREFIX_ACC_ADDR,
    bech32prefixaccpub: process.env.NEXT_PUBLIC_BECH32_PREFIX_ACC_PUB,
    bech32prefixvaladdr: process.env.NEXT_PUBLIC_BECH32_PREFIX_VAL_ADDR,
    bech32prefixvalpub: process.env.NEXT_PUBLIC_BECH32_PREFIX_VAL_PUB,
    bech32prefixconsaddr: process.env.NEXT_PUBLIC_BECH32_PREFIX_CONS_ADDR,
    bech32prefixconspub: process.env.NEXT_PUBLIC_BECH32_PREFIX_CONS_PUB,
    currenciescoindenom: process.env.NEXT_PUBLIC_CURRENCIES_COIN_DENOM,
    currenciescoinminimaldenom: process.env.NEXT_PUBLIC_CURRENCIES_COIN_MINIMAL_DENOM,
    currenciescoindecimals: process.env.NEXT_PUBLIC_CURRENCIES_COIN_DECIMALS,
    currenciescoingeckoid: process.env.NEXT_PUBLIC_CURRENCIES_COIN_GECKO_ID,
    feecurrenciescoindenom: process.env.NEXT_PUBLIC_FEE_CURRENCIES_COIN_DENOM,
    feecurrenciescoinminimaldenom: process.env.NEXT_PUBLIC_FEE_CURRENCIES_COIN_MINIMAL_DENOM,
    feecurrenciescoindecimals: process.env.NEXT_PUBLIC_FEE_CURRENCIES_COIN_DECIMALS,
    feecurrenciescoingeckoid: process.env.NEXT_PUBLIC_FEE_CURRENCIES_COIN_GECKO_ID,
    stakecurrencycoindenom: process.env.NEXT_PUBLIC_STAKE_CURRENCY_COIN_DENOM,
    stakecurrencycoinminimaldenom: process.env.NEXT_PUBLIC_STAKE_CURRENCY_COIN_MINIMAL_DENOM,
    stakecurrencycoindecimals: process.env.NEXT_PUBLIC_STAKE_CURRENCY_COIN_DECIMALS,
    stakecurrencycoingeckoid: process.env.NEXT_PUBLIC_STAKE_CURRENCY_COIN_GECKO_ID,
    gaspricesteplow: process.env.NEXT_PUBLIC_GAS_PRICE_STEP_LOW,
    gaspricestepmedium: process.env.NEXT_PUBLIC_GAS_PRICE_STEP_MEDIUM,
    gaspricestephigh: process.env.NEXT_PUBLIC_GAS_PRICE_STEP_HIGH,
    gaspricestepaverage: process.env.NEXT_PUBLIC_GAS_PRICE_STEP_AVERAGE,
    denom: process.env.NEXT_PUBLIC_DENOM,
    displayDenom: process.env.NEXT_PUBLIC_DISPLAY_DENOM,
    baseDenom: process.env.NEXT_PUBLIC_BASE_DENOM,
    baseExponent: process.env.NEXT_PUBLIC_BASE_EXPONENT,
    name: process.env.NEXT_PUBLIC_NAME,
    prefix: process.env.NEXT_PUBLIC_PREFIX,
    color: process.env.NEXT_PUBLIC_COLOR,
    explorer: process.env.NEXT_PUBLIC_EXPLORER,
    txExplorer: process.env.NEXT_PUBLIC_TX_EXPLORER,
    valExplorer: process.env.NEXT_PUBLIC_VAL_EXPLORER,
    govExplorer: process.env.NEXT_PUBLIC_GOV_EXPLORER,
    logo: process.env.NEXT_PUBLIC_LOGO,
    hyperLink: process.env.NEXT_PUBLIC_HYPERLINK
  });