name: CI
on:
  # Push to long living branches or PRs
  push:
    branches:
      - master
      - main
  pull_request:
    types: [ opened ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run lint

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: cp .env.sample .env.local
      - run: npm run build
      
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2   

    - name: Update the repo from web server
      uses: appleboy/ssh-action@v0.1.4      
      env:
        NODE_OPTIONS: --openssl-legacy-provider
        CI: false
      with:
        host: ${{ secrets.WEB_SERVER }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIV_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        envs: CI, NODE_OPTIONS
        script: |
          cd ~/multisig.notional.ventures
          bash deploy.sh
          
          
